print ("Ola!")
number1= float(int(input("Digite o primeiro número:\n")))
number2= float(int(input("Digite o segundo número:\n")))
number3= float(int(input("Digite o terceiro número:\n")))
media = ((number1+number2+number3)/3)
print(f"A média dos 3 números é ", {media})